In [65]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [66]:
csv_path = "Resources/RDU_2015_19_Delays_Causes_ML.csv"

delays_df = pd.read_csv(csv_path)
delays_df

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK   FL_DATE  \
0       2015        1      1             1            4    1/1/15   
1       2015        1      1             2            5    1/2/15   
2       2015        1      1             3            6    1/3/15   
3       2015        1      1             4            7    1/4/15   
4       2015        1      1             5            1    1/5/15   
...      ...      ...    ...           ...          ...       ...   
230675  2019        4     12            26            4  12/26/19   
230676  2019        4     12            26            4  12/26/19   
230677  2019        4     12            26            4  12/26/19   
230678  2019        4     12            26            4  12/26/19   
230679  2019        4     12            26            4  12/26/19   

       OP_UNIQUE_CARRIER  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  ...  \
0                     AA               1302              14492    RDU  ...   
1                     AA               1302              14492    RDU  ...   
2                     AA               1302              14492    RDU  ...   
3                     AA               1302              14492    RDU  ...   
4                     AA               1302              14492    RDU  ...   
...                  ...                ...                ...    ...  ...   
230675                WN               1593              14492    RDU  ...   
230676                WN               2510              14492    RDU  ...   
230677                WN                864              14492    RDU  ...   
230678                WN               1173              14492    RDU  ...   
230679                WN               2077              14492    RDU  ...   

        CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME AIR_TIME DISTANCE  \
0                    190                188.0    171.0     1061   
1                    190                193.0    160.0     1061   
2                    190                203.0    167.0     1061   
3                    190                212.0    191.0     1061   
4                    190                173.0    154.0     1061   
...                  ...                  ...      ...      ...   
230675               140                114.0    102.0      667   
230676               135                112.0    101.0      667   
230677               105                107.0     88.0      587   
230678               115                 99.0     88.0      587   
230679               115                113.0    100.0      587   

       DISTANCE_GROUP  CARRIER_DELAY  WEATHER_DELAY  NAS_DELAY  \
0                   5            NaN            NaN        NaN   
1                   5          542.0            0.0        3.0   
2                   5            1.0            0.0       13.0   
3                   5            2.0            0.0       22.0   
4                   5            0.0            0.0        0.0   
...               ...            ...            ...        ...   
230675              3            NaN            NaN        NaN   
230676              3            NaN            NaN        NaN   
230677              3            NaN            NaN        NaN   
230678              3            NaN            NaN        NaN   
230679              3            NaN            NaN        NaN   

        SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0                  NaN                  NaN  
1                  0.0                343.0  
2                  0.0                 18.0  
3                  0.0                 28.0  
4                  0.0                 42.0  
...                ...                  ...  
230675             NaN                  NaN  
230676             NaN                  NaN  
230677             NaN                  NaN  
230678             NaN                  NaN  
230679             NaN                  NaN  

[230680 rows x 43 columns]

In [67]:
delays_df.count()

YEAR                   230680
QUARTER                230680
MONTH                  230680
DAY_OF_MONTH           230680
DAY_OF_WEEK            230680
FL_DATE                230680
OP_UNIQUE_CARRIER      230680
OP_CARRIER_FL_NUM      230680
ORIGIN_AIRPORT_ID      230680
ORIGIN                 230680
ORIGIN_WAC             230680
DEST_AIRPORT_ID        230680
DEST                   230680
DEST_CITY_NAME         230680
DEST_STATE_ABR         230680
DEST_WAC               230680
CRS_DEP_TIME           230680
DEP_TIME               226320
DEP_DELAY              226187
DEP_DELAY_NEW          226187
DEP_DEL15              226187
DEP_DELAY_GROUP        226187
DEP_TIME_BLK           230680
CRS_ARR_TIME           230680
ARR_TIME               226087
ARR_DELAY              225562
ARR_DELAY_NEW          225562
ARR_DEL15              225562
ARR_DELAY_GROUP        225562
ARR_TIME_BLK           230680
CANCELLED              230680
CANCELLATION_CODE        4530
DIVERTED               230680
CRS_ELAPSE

In [68]:
delays_df = delays_df.drop(['YEAR','FL_DATE','OP_UNIQUE_CARRIER','OP_CARRIER_FL_NUM','ORIGIN_AIRPORT_ID','ORIGIN','ORIGIN_WAC','DEST_AIRPORT_ID','DEST','DEST_CITY_NAME','DEST_STATE_ABR','DEST_WAC','CRS_DEP_TIME','DEP_TIME','DEP_DELAY','DEP_DELAY_NEW','DEP_DELAY_GROUP','DEP_TIME_BLK','CRS_ARR_TIME','ARR_TIME','ARR_DELAY','ARR_DELAY_NEW','ARR_DELAY_GROUP','ARR_TIME_BLK','CANCELLED','CANCELLATION_CODE','DIVERTED','CRS_ELAPSED_TIME','ACTUAL_ELAPSED_TIME','AIR_TIME','DISTANCE','DISTANCE_GROUP','CARRIER_DELAY','WEATHER_DELAY','NAS_DELAY','SECURITY_DELAY','LATE_AIRCRAFT_DELAY'], axis =1)
delays_df

QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  DEP_DEL15  ARR_DEL15
0             1      1             1            4        1.0        0.0
1             1      1             2            5        1.0        1.0
2             1      1             3            6        1.0        1.0
3             1      1             4            7        1.0        1.0
4             1      1             5            1        1.0        1.0
...         ...    ...           ...          ...        ...        ...
230675        4     12            26            4        0.0        0.0
230676        4     12            26            4        0.0        0.0
230677        4     12            26            4        0.0        0.0
230678        4     12            26            4        0.0        0.0
230679        4     12            26            4        0.0        0.0

[230680 rows x 6 columns]

In [69]:
delays_df.columns

Index(['QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'DEP_DEL15',
       'ARR_DEL15'],
      dtype='object')

In [70]:
delays_df.shape

(230680, 6)

In [71]:
delays_df.dropna(how = 'any').shape

(225436, 6)

In [72]:
delays_df.isnull().sum()

QUARTER            0
MONTH              0
DAY_OF_MONTH       0
DAY_OF_WEEK        0
DEP_DEL15       4493
ARR_DEL15       5118
dtype: int64

In [73]:
delays_df.count()

QUARTER         230680
MONTH           230680
DAY_OF_MONTH    230680
DAY_OF_WEEK     230680
DEP_DEL15       226187
ARR_DEL15       225562
dtype: int64

In [74]:
delays_df = delays_df.fillna({'ARR_DEL15': 1})

In [75]:
delays_df = delays_df.fillna({'DEP_DEL15': 1})

In [76]:
delays_df.dropna(axis=0, how='any', inplace=True)

In [77]:
delays_df.count()

QUARTER         230680
MONTH           230680
DAY_OF_MONTH    230680
DAY_OF_WEEK     230680
DEP_DEL15       230680
ARR_DEL15       230680
dtype: int64

In [78]:
delays_df.to_csv('/Users/mikaelshall/Desktop/DelaysCSV/delays2.csv',index=False)

In [79]:
delays_df

QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  DEP_DEL15  ARR_DEL15
0             1      1             1            4        1.0        0.0
1             1      1             2            5        1.0        1.0
2             1      1             3            6        1.0        1.0
3             1      1             4            7        1.0        1.0
4             1      1             5            1        1.0        1.0
...         ...    ...           ...          ...        ...        ...
230675        4     12            26            4        0.0        0.0
230676        4     12            26            4        0.0        0.0
230677        4     12            26            4        0.0        0.0
230678        4     12            26            4        0.0        0.0
230679        4     12            26            4        0.0        0.0

[230680 rows x 6 columns]

In [80]:
# Prediction of Arrival Delay 

from sklearn.linear_model import LinearRegression 

In [81]:
X = delays_df.drop(columns=['ARR_DEL15'])
y = delays_df.loc[:,['ARR_DEL15']]

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1,random_state=62)

clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [83]:
X_test.head(1)

QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  DEP_DEL15
208579        3      8            29            4        0.0

In [84]:
# x = [QUARTER, MONTH, DAY_OF_MONTH, DAY_OF_WEEK, DEP_DEL15]
# QUARTER 1 - 4 
# MONTH 1 - 12
# DAY_OF_MONTH 1 - 30
# DAY_OF_WEEK 1 - 7 
# DEP_DEL15 0 or 1; 0 if it is not delayed, 1 it is. 

x = [4, 12, 20, 5, 0]

In [85]:
clf.predict([x])

array([[0.05082192]])

In [86]:
# If you change the Arrival Delay to 1, chances are a Departure Delay are possible. 

x = [4, 12, 20, 5, 1]

clf.predict([x])

array([[0.81101902]])

In [87]:
# Prediction of Departure Delay 

X = delays_df.drop(columns=['DEP_DEL15'])
y = delays_df.loc[:,['DEP_DEL15']]

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1,random_state=62)

clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [89]:
# p = [QUARTER, MONTH, DAY_OF_MONTH, DAY_OF_WEEK, ARR_DEL15]
# QUARTER  1 - 4
# MONTH  1 - 12
# DAY_OF_MONTH  1 - 30
# DAY_OF_WEEK  1 - 7
# ARR_DEL15  0 or 1 

x = [4, 12, 24, 5, 0]

clf.predict([x])

array([[0.04482445]])

In [90]:
# If you change the Arrival Delay to 1, chances are a Depature Delay will be possible.

# p = [QUARTER, MONTH, DAY_OF_MONTH, DAY_OF_WEEK, ARR_DEL15]
x = [4, 12, 20, 5, 1]
clf.predict([x])

array([[0.78457408]])

In [93]:
# Use RFC to identify which flight factor has the most the most significance on flight delays

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X,y)
rf.score(X,y)

/Users/mikaelshall/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


0.9191780821917809

In [96]:
delay_factors = rf.feature_importances_
delay_factors = sorted(zip(importances, X), reverse=True)
delay_factors

[(0.9400329706082897, 'ARR_DEL15'),
 (0.036132140662780365, 'DAY_OF_MONTH'),
 (0.012690623606095465, 'DAY_OF_WEEK'),
 (0.009367481156252102, 'MONTH'),
 (0.001776783966582374, 'QUARTER')]

In [97]:
classifier.classes_

array([0., 1.])

In [40]:
#Make predictions 
predcictions = classifier.predict_proba(X_test)
print(f"First 200 Predictions:   {predictions[:200]}")
print(f"First 200 Actual lablels: {y_test[:200].tolist()}")

First 200 Predictions:   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
First 200 Actual lablels: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0